name: Deploy para AWS Serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy para Produção
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, pdo_pgsql, pgsql, bcmath, intl
          tools: composer:v2

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependências do PHP (Composer)
        run: composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction

      - name: Build do Frontend (Vite)
        run: |
          npm ci
          npm run build

      - name: Instalar Serverless Framework
        run: npm install -g serverless

      - name: Deploy Serverless
        run: serverless deploy --stage prod --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
