useDotenv: true
service: laravel
frameworkVersion: '3'

# Set your team ID if you are using Bref Cloud (https://bref.sh/cloud)
#bref:
#    team: my-team-id

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    stage: dev
    role: arn:aws:iam::347189815304:role/LabRole
    # Environment variables
    environment:
        APP_ENV: production
        # Replace with a secret variable: https://bref.sh/docs/environment/variables#secrets
        APP_KEY: ${env:APP_KEY}
        APP_DEBUG: ${param:debug}
        # Uncomment the line below if you uncomment `constructs.website`
        
        APP_URL: https://qktuepw0x4.execute-api.us-east-1.amazonaws.com
        ASSET_URL: https://qktuepw0x4.execute-api.us-east-1.amazonaws.com

        SESSION_DRIVER: cookie # Change to database if you have set up a database
        # Maintenance mode: https://bref.sh/docs/laravel/maintenance-mode
        MAINTENANCE_MODE: ${param:maintenance, null}
        # Logging configuration: https://bref.sh/docs/environment/logs
        LOG_CHANNEL: stderr
        LOG_STDERR_FORMATTER: Bref\Monolog\CloudWatchFormatter
        # Database configuration: https://bref.sh/docs/environment/database
        DB_CONNECTION: pgsql
        DB_HOST: aws-1-sa-east-1.pooler.supabase.com
        DB_PORT: 6543
        DB_DATABASE: postgres
        DB_USERNAME: postgres.sqdvzczxyuttxjwmlbbi
        DB_PASSWORD: ${env:DB_PASSWORD}

        # Queue configuration: https://bref.sh/docs/laravel/queues
        #QUEUE_CONNECTION: sqs
        #SQS_QUEUE: ${construct:jobs.queueUrl}
        # Filesystem configuration: https://bref.sh/docs/laravel/filesystem
        #FILESYSTEM_DISK: s3
        #AWS_BUCKET: ${construct:storage.bucketName}

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-84-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-84-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

# Environment-specific parameters
# See https://github.com/oss-serverless/serverless/blob/main/docs/guides/parameters.md
params:
    default:
        # Laravel's APP_ENV. See https://bref.sh/docs/laravel/environments
        appEnv: ${sls:stage}
        debug: 0
    prod:
        # Laravel expects "production" for `app()->isProduction()` to work correctly
        appEnv: production
    dev:
        debug: 1 # Enable debug in `dev`

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!.env' # Don't deploy local config
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!resources/css/**'
        - '!resources/images/**'
        - '!resources/js/**'
        - '!storage/**'
        - '!tests/**'
        - '!database/*.sqlite'
        - 'public/build/**'

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
